import type { SearchConfig } from "./schema";

export const DEFAULT_KEYWORDS: string[] = [
  "yazılım etkinliği",
  "developer meetup",
  "software meetup",
  "startup etkinliği",
  "girişimcilik etkinliği",
  "teknoloji etkinliği",
  "teknoloji konferansı",
  "AI event",
  "artificial intelligence",
  "yapay zekâ etkinliği",
  "hackathon",
  "startup meetup",
  "networking event",
  "founder meetup",
  "SaaS event",
  "product meetup",
  "developer conference",
  "software conference",
  "girişimci buluşması",
  "startup networking",
  "teknoloji zirvesi",
  "workshop",
  "bootcamp",
  "demo day",
  "pitch event",
];

export const DEFAULT_HASHTAGS: string[] = [
  "yazılım",
  "startup",
  "girişimcilik",
  "teknoloji",
  "yapayzeka",
  "artificialintelligence",
  "meetup",
  "hackathon",
  "developer",
  "networking",
  "saas",
  "founder",
  "demoday",
];

export const DEFAULT_SEARCH_CONFIG: SearchConfig = {
  version: 1,
  enabledPlatforms: ["linkedin", "x"],
  preferredCountry: "TR",
  defaultTimeZone: "Europe/Istanbul",
  keywords: DEFAULT_KEYWORDS,
  hashtags: DEFAULT_HASHTAGS,
  filters: {
    city: null,
    lastDays: 30,
    includeOnline: true,
    includeExpired: false,
    unknownPublishedAt: "exclude_from_date_filtered_results",
  },
  limits: {
    maxPostsPerQuery: 15,
    maxScrollsPerQuery: 3,
    minDelayMs: 4000,
    maxDelayMs: 8000,
    maxRunMinutes: 60,
  },
  ocr: {
    enabled: true,
    maxImagesPerPost: 2,
    minImageBytes: 20000,
  },
};
